# GRPO_Trainer/inference_logreg_tfidf.py

import joblib
import logging
import os
from sklearn.feature_extraction.text import TfidfVectorizer # We need this again

# Configure logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

# --- Configuration ---
# Define paths relative to the script's location (GRPO_Trainer)
MODEL_DIR = "models"
MODEL_FILENAME = "supervised_logreg_tfidf.joblib"
VECTORIZER_FILENAME = "tfidf_vectorizer.joblib" # Make sure this matches how it was saved in utils.py
LABEL_ENCODER_FILENAME = "label_encoder.joblib"

MODEL_PATH = os.path.join(MODEL_DIR, MODEL_FILENAME)
VECTORIZER_PATH = os.path.join(MODEL_DIR, VECTORIZER_FILENAME)
LABEL_ENCODER_PATH = os.path.join(MODEL_DIR, LABEL_ENCODER_FILENAME)

# --- Load Artifacts ---
try:
    logging.info(f"Loading model from: {MODEL_PATH}")
    model = joblib.load(MODEL_PATH)
    logging.info("Model loaded successfully.")

    logging.info(f"Loading TF-IDF vectorizer from: {VECTORIZER_PATH}")
    vectorizer = joblib.load(VECTORIZER_PATH)
    logging.info("Vectorizer loaded successfully.")

    logging.info(f"Loading label encoder from: {LABEL_ENCODER_PATH}")
    label_encoder = joblib.load(LABEL_ENCODER_PATH)
    logging.info("Label encoder loaded successfully.")

except FileNotFoundError as e:
    logging.error(f"Error loading artifacts: {e}. Please ensure the model, vectorizer, and label encoder files exist in the '{MODEL_DIR}' directory and were generated by running a training script (like supervised_baseline.py with TF-IDF).")
    exit() # Exit if artifacts can't be loaded
except Exception as e:
    logging.error(f"An unexpected error occurred during loading: {e}")
    exit()


def predict_diagnosis(clinical_note_text):
    """
    Predicts the diagnosis for a given clinical note using the loaded model.

    Args:
        clinical_note_text (str): The raw clinical note text.

    Returns:
        str: The predicted diagnosis name, or None if prediction fails.
    """
    if not isinstance(clinical_note_text, str) or not clinical_note_text.strip():
        logging.error("Input clinical note must be a non-empty string.")
        return None

    try:
        # 1. Vectorize the input text using the loaded TF-IDF vectorizer
        # transform expects an iterable, so pass the text in a list
        logging.info("Vectorizing input text...")
        vectorized_note = vectorizer.transform([clinical_note_text])
        logging.info(f"Vectorized shape: {vectorized_note.shape}")

        # 2. Predict the diagnosis label using the loaded model
        logging.info("Predicting diagnosis label...")
        predicted_label_numeric = model.predict(vectorized_note)
        logging.info(f"Predicted numeric label: {predicted_label_numeric}")

        # 3. Convert the numeric label back to the diagnosis name
        predicted_diagnosis_name = label_encoder.inverse_transform(predicted_label_numeric)

        # inverse_transform returns an array, get the first element
        return predicted_diagnosis_name[0]

    except Exception as e:
        logging.error(f"Error during prediction: {e}")
        return None


# --- Main Execution ---
if __name__ == "__main__":
    # Example usage:
    example_note = """
        "Gender: Male

 Age: 48 years

 Chief_complaint: ► **Cold, Sneezing** :  
• 2 Days.  
• Precipitating factors - Cold weather, Wind.  
• Prior treatment sought - None.  
► **Shoulder, arm or hand pain** :  
• Site - Shoulder, Back, Elbow.  
• Involvement - Bilateral.  
• Duration - 7 Days.  
• Onset - Gradual.  
• Progress - Recurring/relapsing.  
• Pain characteristics - Sharp shooting.  
• Patient has no history of trauma.  
• Aggravating factors - वरती हात केल्यावर ताण पडतो दुखतो हात.  
• Prior treatment sought - None.  
► **Associated symptoms** :  
• Patient reports -  
Nasal congestion/Stuffy nose, Runny nose, दोन्ही हात दुखतात खांदे दुखतात  
• Patient denies -  
Fever, Itchy throat, Cough, Headache, Body pain, Chills, Chest
pain/discomfort, Night sweats, Swelling in the painful area, Redness in the
painful area, Stiffness, Deterioration in dail

 Physical_examination: **General exams:**  
• Eyes: Jaundice-no jaundice seen, [picture taken].  
• Eyes: Pallor-normal pallor, [picture taken].  
• Arm-Pinch skin* - pinch test normal.  
• Nail abnormality-nails normal, [picture taken].  
• Nail anemia-Nails are not pale, [picture taken].  
• Ankle-no pedal oedema, [picture taken].  
**Joint:**  
• tenderness seen, [picture taken].  
• no deformity around joint.  
• full range of movement is seen.  
• joint is not swollen.  
• pain during movement, [picture taken].  
• no redness around joint.

 Patient_medical_history: • Allergies - No known allergies.  
• Alcohol use - No.  
• Smoking history - Patient denied/has no h/o smoking.  
• Medical History - None.  
• Drug history - No recent medication.  

 Family_history: •Do you have a family history of any of the following? : None.  

 Vitals:- 

Sbp: 122.0

 Dbp: 79.0

 Pulse: 83.0

 Temperature: 36.56 'C

 Weight: 48.0 Kg

 Height: 156.0 cm

 BMI: 19.72

 RR: 22.0

 SPO2: 98.0

 HB: Null

 Sugar_random: Null

 Blood_group: Null

 Sugar_pp: Null

 Sugar_after_meal: Null

"

    """

    print("-" * 30)
    print(f"Input Clinical Note:\n{example_note}")
    print("-" * 30)

    predicted_diagnosis = predict_diagnosis(example_note)

    if predicted_diagnosis:
        print(f"Predicted Diagnosis: {predicted_diagnosis}")
    else:
        print("Prediction failed.")

    print("-" * 30)

    # Example 2:
    example_note_2 = """
        "Gender: Female

 Age: 43 years

 Chief_complaint: ► **Fatigue and General weakness** :  
• Duration - 2 महिने.  
• Timing - All day.  
• Eating habits - 2, patient is irregular in taking meals, Amount, Small, पोळी
भाजी .  
• Stressful condition - No.  
• Prior treatment sought - None.  
► **Associated symptoms** :  
• Patient reports -  
Heat / Cold intolerance - Cold intolerance, Muscle weakness, Daytime
sleepiness, Disturbed sleep, हात पायाला मुंग्या येतात  
• Patient denies -  
Fever, Chills, Night sweats, Breathlessness on exertion, Jaundice, Bleeding,
Paresthesia, Gait abnormalities, Drooping eyelids, Depressed mood, Anxiety,
Joint pain, Increase in quantity of urine output, Increase in frequency of
urination, Polydipsia, Polyphagia  

 Physical_examination: **General exams:**  
• Eyes: Jaundice-no jaundice seen, [picture taken].  
• Eyes: Pallor-normal pallor, [picture taken].  
• Arm-Pinch skin* - pinch test normal.  
• Nail abnormality-nails normal, [picture taken].  
• Nail anemia-Nails are not pale, [picture taken].  
• Ankle-no pedal oedema.  
**Neck:**  
• Thyroid swelling-no swelling in front of neck.  
**Joint:**  
• no deformity around joint.  
• joint is not swollen.  
• pain during movement.  
**Face:**  
• face appears normal.  
**Leg:**  
• Strength-both legs have equal strength.  
**Any Location:**  
• Skin Bruise:-no bruises seen.  
• Skin Rash:-no rash.  
**Hands:**  
• Holding a paper tightly between thumb and curled fingers-grip equal on both
sides.  
• Gripping two fingers tightly-grip equal on both sides.  
• Ability to spread 4 fingers apart when they are held together-grip equal on
both sides.  
**Head:** <br

 Patient_medical_history: • Pregnancy status - Not pregnant.  
• Allergies - No known allergies.  
• Alcohol use - No.  
• Smoking history - Patient denied/has no h/o smoking.  
• Medical History - None.  
• Drug history - No recent medication.  

 Family_history: •Do you have a family history of any of the following? : None.  

 Vitals:- 

Sbp: 110.0

 Dbp: 80.0

 Pulse: 102.0

 Temperature: 36.94 'C

 Weight: 47.35 Kg

 Height: 155.0 cm

 BMI: 19.71

 RR: 21.0

 SPO2: 100.0

 HB: Null

 Sugar_random: Null

 Blood_group: Null

 Sugar_pp: Null

 Sugar_after_meal: Null

"
    """

    print(f"Input Clinical Note:\n{example_note_2}")
    print("-" * 30)
    predicted_diagnosis_2 = predict_diagnosis(example_note_2)
    if predicted_diagnosis_2:
        print(f"Predicted Diagnosis: {predicted_diagnosis_2}")
    else:
        print("Prediction failed.")
    print("-" * 30) 